# Generated by Django 5.0.4 on 2024-05-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VishalaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fees',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
